config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match "contact" => "contacts#create", :via => :post, as: "contacts"
  match "schedule" => "pages#schedule", :via => :get, as: "schedule"
  match "about-us" => "pages#about_us", :via => :get, as: "about_us"
  match "services" => "pages#services", :via => :get, as: "services"
  match "contact" => "pages#contact", :via => :get, as: "contact"
  
  resources :learning_materials, only: %I[index show]

  #banner images
  resources :banner_images do
    match 'move_up' => 'banner_images#move_up', via: :post, as: 'move_up'
    match 'move_down' => 'banner_images#move_down', via: :post, as: 'move_down'
  end

  namespace :admin do
    resources :users do
      member do
        get :sign_in_logs
      end
    end
    resources :learning_materials do
      member do
        get :download_logs
      end

      collection do
        post :s3_upload
      end
    end
  end

  match 'admin' => 'banner_images#index', via: :get

  # programmes
  match "programmes/:id" => "programmes#index", :via => :get, as: "programmes"

  root 'pages#home'
end  

app/models/banner_image.rb
# == Schema Information
#
# Table name: banner_images
#
#  id         :integer          not null, primary key
#  image_url  :string
#  position   :integer
#  created_at :datetime
#  updated_at :datetime
#

class BannerImage < ActiveRecord::Base
  acts_as_list

end

app/controllers/banner_images_controller.rb
class BannerImagesController < Admin::BaseController
  before_action :authenticate_user!, except: %I[create]

  def index
    @banner_images = BannerImage.order("position")
  end

  def create
    @banner_image = BannerImage.create(image_url: params[:url])
  end

  def destroy
    @banner_image = BannerImage.find(params[:id])
    if @banner_image.destroy
      flash[:success] = 'Deleted image.'
      redirect_to banner_images_path
    end
  end

  def move_up
    @banner_image = BannerImage.find(params[:banner_image_id])
    @banner_image.move_higher
    redirect_to banner_images_path
  end

  def move_down
    @banner_image = BannerImage.find(params[:banner_image_id])
    @banner_image.move_lower
    redirect_to banner_images_path
  end

end

app/views/banner_images/_tr_image.html.erb
<tr>
  <td><%= banner_image.position %></td>
  <td>
    <div class="image-class">
      <%= image_tag banner_image.image_url, class: 'img-thumbnail' %>
    </div>
  </td>
  <td>
    <%= link_to "<i class='fa fa-arrow-up'></i>".html_safe,
        banner_image_move_up_path(banner_image),
        method: :post %>
    <%= link_to "<i class='fa fa-arrow-down'></i>".html_safe,
        banner_image_move_down_path(banner_image),
        method: :post %>

  </td>
  <td>
    <%= link_to 'Delete', banner_image_path(banner_image), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/banner_images/create.js.erb
$(".banner-image-table").find('tbody').append("<%= j render partial: 'banner_images/tr_image', locals: { banner_image: @banner_image } %>")
$('.modal').modal('hide');

app/views/banner_images/index.html.erb
<%= render partial: "admin/tab", locals: { tab: "home_banners" } %>
<h3>Banner Images</h3>
<hr/>
<div class="pull-right">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#uploadModal">
    Upload image
  </button>
</div>
<table class="table banner-image-table">
  <thead>
    <th>Position</th>
    <th>Image</th>
    <th>Action</th>
    <th>Delete</th>
  </thead>
  <tbody>
    <% @banner_images.each do |banner_image| %>
      <%= render partial: 'banner_images/tr_image', locals: { banner_image: banner_image } %>
    <% end %>
  </tbody>
</table>

<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Upload image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= s3_uploader_form callback_url: banner_images_url, class: 'form', id: "S3-uploader", callback_param: "attachment[direct_upload_url]", max_file_size: 5000.megabytes do %>

            <%= file_field_tag :file %>
            <script id="template-upload" type="text/x-tmpl">
              <div id="file-{%=o.unique_id%}" class="upload">
                {%=o.name%}
                <div class="progress">
                  <div class="bar" style="width: 0%"></div>
                </div>
              </div>
            </script>

          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>