config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match "contact" => "contacts#create", :via => :post, as: "contacts"
  match "schedule" => "pages#schedule", :via => :get, as: "schedule"
  match "about-us" => "pages#about_us", :via => :get, as: "about_us"
  match "services" => "pages#services", :via => :get, as: "services"
  match "contact" => "pages#contact", :via => :get, as: "contact"
  
  resources :learning_materials, only: %I[index show]

  #banner images
  resources :banner_images do
    match 'move_up' => 'banner_images#move_up', via: :post, as: 'move_up'
    match 'move_down' => 'banner_images#move_down', via: :post, as: 'move_down'
  end

  namespace :admin do
    resources :users do
      member do
        get :sign_in_logs
      end
    end
    resources :learning_materials do
      member do
        get :download_logs
      end

      collection do
        post :s3_upload
      end
    end
  end

  match 'admin' => 'banner_images#index', via: :get

  # programmes
  match "programmes/:id" => "programmes#index", :via => :get, as: "programmes"

  root 'pages#home'
end  

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  has_many :login_activities, as: :user
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %I[show edit update sign_in_logs]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Created new user."
      redirect_to admin_users_path
    else
      flash[:alert] = @user.errors.full_messages.join
      render :new
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Updated successfully."
      redirect_to admin_users_path
    else
      flash[:alert] = @user.errors.full_messages.join
      render :edit
    end
  end

  def sign_in_logs
    @sign_in_logs = @user.login_activities.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  private
  def user_params
    columns = %I[email username password password_confirmation role]
    params.require(:user)
    .permit(columns)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
= form_for [:admin, @user] do |f|
  .form-group
    = f.label :email, "Email", class: "col-sm-2 control-label"
    .col-sm-10
      = f.email_field :email, class: "form-control", placeholder: "Email", required: true
  
  .form-group
    = f.label :password, "Password", class: "col-sm-2 control-label"
    .col-sm-10
      = f.password_field :password, class: "form-control", placeholder: "Password"
  
  .form-group
    = f.label :password_confirmation, "Password Confirmation", class: "col-sm-2 control-label"
    .col-sm-10
      = f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"

  .form-group
    = f.label :role, "Role", class: "col-sm-2 control-label"
    .col-sm-10
      = f.select :role, options_for_select(["user", "admin"], @user.role), {}, class: "form-control", required: true
  
  
  form-group
    .col-sm-2.col-sm-offset-2
      = link_to "Cancel", admin_users_path, class: "btn btn-white"
      = f.submit "Submit", class: "btn btn-primary"
    

app/views/admin/users/edit.html.slim
= render partial: "admin/tab", locals: { tab: "users" }
.row
  .col-12
    .float-left
      h5 Edit Users
hr/

= render "form"

app/views/admin/users/index.html.slim
= render partial: "admin/tab", locals: { tab: "users" }
.row
  .col-12
    .float-left
      h5 Users
    .float-right
      = link_to "Create User", new_admin_user_path, class: "btn btn-primary btn-sm"

hr/
.table-responsive
  table.table
    thead
      tr
        th #
        th Email
        th Name
        th Role
        th Action
    tbody
      - @users.each do |user|
        tr 
          td = user.id
          td = user.email
          td = user.email
          td = user.role
          td 
            = link_to "Edit", edit_admin_user_path(user), class: "btn btn-primary btn-sm mr-2"
            = link_to "Sign in logs", sign_in_logs_admin_user_path(user), class: "btn btn-warning btn-sm"
  

app/views/admin/users/new.html.slim
= render partial: "admin/tab", locals: { tab: "users" }
.row
  .col-12
    .float-left
      h5 New Users
hr/

= render "form"

app/views/admin/users/sign_in_logs.html.slim
= render partial: "admin/tab", locals: { tab: "users" }
.row
  .col-12
    .float-left
      h5 = "#{@user.email}'s signed in logs"
hr/

table.table
  thead
    tr
      th Sign in Time

  tbody
    - @sign_in_logs.each do |sign_in_log|
      tr
        td = sign_in_log.created_at.in_time_zone

.row
  .col-12
    .justify-content-center
      = will_paginate @sign_in_logs, renderer: WillPaginate::ActionView::BootstrapLinkRenderer