config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match "contact" => "contacts#create", :via => :post, as: "contacts"
  match "schedule" => "pages#schedule", :via => :get, as: "schedule"
  match "about-us" => "pages#about_us", :via => :get, as: "about_us"
  match "services" => "pages#services", :via => :get, as: "services"
  match "contact" => "pages#contact", :via => :get, as: "contact"
  
  resources :learning_materials, only: %I[index show]

  #banner images
  resources :banner_images do
    match 'move_up' => 'banner_images#move_up', via: :post, as: 'move_up'
    match 'move_down' => 'banner_images#move_down', via: :post, as: 'move_down'
  end

  namespace :admin do
    resources :users do
      member do
        get :sign_in_logs
      end
    end
    resources :learning_materials do
      member do
        get :download_logs
      end

      collection do
        post :s3_upload
      end
    end
  end

  match 'admin' => 'banner_images#index', via: :get

  # programmes
  match "programmes/:id" => "programmes#index", :via => :get, as: "programmes"

  root 'pages#home'
end  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div id="googleMap"></div>
        <br/>
        <br/>
      </div>

      <div class="col-md-4">
        <p class="title">Get in touch</p>
        <div class="row contact-detail">
          <div class="col-1">
            <i class="fa fa-phone red-font"></i>
          </div>

          <div class="col-10">
            +60374993365
          </div>
        </div>

        <div class="row contact-detail">
          <div class="col-1">
            <i class="fa fa-envelope-o red-font"></i>
          </div>

          <div class="col-10">
            <%= mail_to "info@jtstrainings.com", "info@jtstrainings.com", :class => "white-link", :target => "_blank" %>
          </div>
        </div>

        <div class="row contact-detail">
          <div class="col-1">
            <i class="fa fa-globe red-font"></i>
          </div>

          <div class="col-10">
            <%= link_to "www.jtstrainings.com", "www.jtstrainings.com", :class => "white-link" %>
          </div>
        </div>

        <div class="row contact-detail">
          <div class="col-1">
            <i class="fa fa-facebook red-font"></i>
          </div>

          <div class="col-10">
            <%= link_to "facebook.com/jtstrainings", "https://www.facebook.com/jtstrainings/", :class => "white-link", :target => "_blank" %>
          </div>
        </div>

        <div class="row contact-detail">
          <div class="col-1">
            <i class="fa fa-map red-font"></i>
          </div>

          <div class="col-10">
            No. 288 (Room 1),
            Jalan Bahagia SS6, Kelana Jaya,
            47301 Petaling Jaya, Selangor.
          </div>
        </div>

        <br/>
        <br/>

      </div>

      <div class="col-md-5">
        <p class="title">Enquiry</p>

        <% @contact = Contact.new %>
        <div class="row">
          <div class="col-md-12">
            <%= form_for @contact, :html => {:class => "contact-form row"}, :remote => true do |f| %>
              
              <%= f.label :name, "Name", :class => "col-md-3" %>
              <div class="col-sm-9">
                <%= f.text_field :name, :placeholder => "Name", :class => "form-control mr-sm-2", :required => true %>
                <div class="mb-3"></div>
              </div>

              
              <%= f.label :company_name, "Company", :class => "col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :company_name, :placeholder => "Company Name", :class => "form-control mr-sm-2", :required => true %>
                  <div class="mb-3"></div>
                </div>
                

              
              <%= f.label :email, "Email", :class => "col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.email_field :email, :placeholder => "Email", :class => "form-control mr-sm-2", :required => true %>
                  <div class="mb-3"></div>
                </div>
                

              
              <%= f.label :contact, "Contact", :class => "col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_field :contact, :placeholder => "Contact", :class => "form-control mr-sm-2", :required => true %>
                  <div class="mb-3"></div>
                </div>
                

              
              <%= f.label :message, "Message", :class => "col-sm-3" %>
                <div class="col-sm-9">
                  <%= f.text_area :message, :placeholder => "Message", :class => "form-control mr-sm-2", :required => true %>
                  <div class="mb-3"></div>
                </div>
                
              <%= recaptcha_tags %>

              <br/>
              <div class="col-sm-12">
                <div class="pull-right">
                  <%= f.submit "Send", :class => "btn btn-primary red-button" %>
                </div>
              </div>
              <br/>
              <br/>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<script>
  function initialize() {
    var myLatlng = new google.maps.LatLng(3.1071759,101.5987406);
    var mapProp = {
      center: myLatlng,
      zoom:17,
      mapTypeId:google.maps.MapTypeId.ROADMAP
    };
    var map=new google.maps.Map(document.getElementById("googleMap"), mapProp);

    var marker = new google.maps.Marker({
      position: myLatlng,
      title:"JTS Trainings"
    });
    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-header
  .container
    button.navbar-toggler aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo03" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    = link_to root_path, class: "navbar-brand navbar-logo" do 
      = image_tag "header_logo.png"
      span JTS TRAININGS SDN BHD
    #navbarTogglerDemo03.collapse.navbar-collapse
      ul.navbar-nav.ml-auto.mt-2.mt-lg-0
        li.nav-item class="#{'active' if (params[:controller] == 'pages' and params[:action] == 'home') }"
          = link_to "HOME", root_path
        
        li.nav-item class="#{'active' if (params[:controller] == 'pages' and params[:action] == 'about_us') }"
          = link_to "ABOUT US", about_us_path

        li.nav-item class="#{'active' if (params[:controller] == 'pages' and params[:action] == 'services') }"
          = link_to "SERVICES", services_path 

        li.nav-item class="#{'active' if (params[:controller] == 'learning_materials') }"
          = link_to "E-LEARNING", learning_materials_path 
        
        li.nav-item.dropdown class="#{'active' if (params[:controller] == 'programmes') }"
          a#navbarDropdown.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
            | PROGRAMME
          .dropdown-menu aria-labelledby="navbarDropdown" 
            - all_programmes.each do |key, value|
              = link_to key, programmes_path(value), class: "dropdown-item"
        
        li.nav-item class="#{'active' if (params[:controller] == 'pages' and params[:action] == 'schedule') }"
          = link_to "SCHEDULE", schedule_path 

        li.nav-item class="#{'active' if (params[:controller] == 'pages' and params[:action] == 'contact') }"
          = link_to "CONTACT", contact_path 

        - if user_signed_in?
          li.nav-item.dropdown
            a#userDropdown.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
              i.fa.fa-user
            .dropdown-menu.dropdown-menu-right aria-labelledby="userDropdown" 
              - if current_user.role == "admin"
                = link_to 'Banner images', banner_images_path, class: "dropdown-item"
                = link_to 'Manage users', admin_users_path, class: "dropdown-item"
                = link_to 'Manage learning materials', admin_learning_materials_path, class: "dropdown-item"
              = link_to 'Logout', destroy_user_session_path, method: 'delete', class: "dropdown-item"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  <meta charset="utf-8">
  <meta name=viewport content="width=device-width, initial-scale=1.0, minimum-scale=0.5 maximum-scale=1.5">

  <meta name="title" content="JTS Trainings" >
  <meta name="description" content="JTS Trainings has a dynamic and creative team that can help you in provide the right training solutions. We had experience in conducting thousands of training courses and have hundreds of business partners in Malaysia.">
  <meta name="keywords" content="jts trainings, training company, team building">

  <title>JTS Trainings</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDirlvVXAxiLosOZ1C8dN4lsdLlDdO5ZLI&callback=initMap" async defer></script>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129442180-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-129442180-1');
  </script>

</head>
<body>
  <%= render "layouts/header" %>
  <div class="body-content">
    <%= yield :banner %>
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>